# Generated by Django 4.1.5 on 2023-01-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="titulo_post",
            field=models.CharField(max_length=255, verbose_name="Título"),
        ),
    ]
