# Generated by Django 4.1.5 on 2023-01-16 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("categorias", "0002_alter_categoria_nome_cat"),
        ("posts", "0002_alter_post_titulo_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="autor_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Autor",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="categoria_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="categorias.categoria",
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="data_post",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data"
            ),
        ),
    ]
