# Generated by Django 4.1.5 on 2023-01-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comentarios", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comentario",
            old_name="omentario",
            new_name="comentario",
        ),
    ]
