# Generated by Django 4.1.5 on 2023-01-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categorias", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="nome_cat",
            field=models.CharField(max_length=100, verbose_name="Categoria"),
        ),
    ]
